package View;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class frmMenuApotik extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public frmMenuApotik() {
        initComponents();
        setTitle("Apotik Setiap Hari Berkah");
        setSize(1000,600);
        setLocationRelativeTo(this);
        Koneksi.Database.KoneksiDB();
        MenuKeluar.setText("Keluar");
        MenuKeluar.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKeluarActionPerformed(evt);
            }
        });
        MenuFile.add(MenuKeluar);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        MenuEntriDataObat = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        MenuKeluar = new javax.swing.JMenuItem();
        MenuLaporan = new javax.swing.JMenu();
        DaftarObat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuFile.setText("File");

        MenuEntriDataObat.setText("Entri Data Obat");
        MenuEntriDataObat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuEntriDataObatActionPerformed(evt);
            }
        });
        MenuFile.add(MenuEntriDataObat);
        MenuFile.add(jSeparator3);

        MenuKeluar.setText("Keluar");
        MenuFile.add(MenuKeluar);

        jMenuBar1.add(MenuFile);

        MenuLaporan.setText("Laporan");

        DaftarObat.setText("Daftar Obat");
        MenuLaporan.add(DaftarObat);

        jMenuBar1.add(MenuLaporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuEntriDataObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuEntriDataObatActionPerformed
        View.frmObat objMhs = new View.frmObat();
        objMhs.setVisible(true);
    }//GEN-LAST:event_MenuEntriDataObatActionPerformed
    private void MenuKeluarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        int pilih = JOptionPane.showConfirmDialog(
                this,
                "Apakah Anda yakin ingin keluar?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (pilih == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }       
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem DaftarObat;
    private javax.swing.JMenuItem MenuEntriDataObat;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JMenuItem MenuKeluar;
    private javax.swing.JMenu MenuLaporan;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
